#!/bin/zsh
#
 # TODO: Move to Python using PowerWalk.
#
if isHelpOption "$1"; then
    cat <<EOF
Usage: countExtensions [files]
    Count how many files of each extension occur below current directory.
    Files with no extension are ignored.
EOF
    exit
fi

command ls -R |\
    grep -v ':$' |\
    sed 's/^.*\///' |\
    grep -E '\.[a-zA-Z][.a-zA-Z0-9_]{0,12}$' |\
    sed 's/^.*\././' |\
    grep -v '[^.a-zA-Z0-9_]' |\
    sort |\
    uniq -c |\
    sort -rn

