#!/usr/bin/env zsh
#
# lowerExtension: Force extensions to lower-case
# <2012-03-01: Written by Steven J. DeRose.

#
if isHelpOption "$1"; then
    cat <<EOF
Usage: lowerExtension [files]
    Force extensions of the listed files, to lower-case."
See also:
    renameFiles --lowerExtensions
EOF
    exit
fi

if ! [[ -e "$1" ]]; then
    echo "File not specified or not found."
    exit
fi

for x in $*; do
   set e = $x:e
   set r = $x:r
   set elower = `echo $e | tr '[:upper:]' '[:lower:]'`
   set newname = $r.$elower
   echo $x "-->" $newname
   mv $x $newname
done
